checks:
  method-complexity:
    enabled: true
    config:
      threshold: 50 # 函数复杂度的阈值为 50
  method-lines:
    enabled: true
    config:
      threshold: 200 # 函数行数的阈值为 200
  file-lines:
    enabled: true
    config:
      threshold: 800 # 文件行数的阈值为 800
exclude_patterns:
- "test/"
- "**/.eslintrc.cjs"
- "**/babel.config.cjs"